databases:
  - name: blog-db
    databaseName: blog_production
    user: blog
    plan: free

services:
  - type: web
    name: blog
    runtime: ruby
    plan: free
    buildCommand: ./bin/build.sh
    startCommand: bundle exec rails server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - kay: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
